name: publish
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      TZ: America/Los_Angeles
      KEY: ${{ secrets.KEY }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      SYSTEM_ID: ${{ secrets.SYSTEM_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - run: ruby index.rb >> "$GITHUB_ENV"
      - run: cat index.html
      - run: npm install libsodium-wrappers
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const sodium = require('libsodium-wrappers')
            await sodium.ready

            const { data: { key, key_id } } = await github.rest.actions.getRepoPublicKey(context.repo)

            const binsec = sodium.from_string(process.env.REFRESH_TOKEN)
            const binkey = sodium.from_base64(key, sodium.base64_variants.ORIGINAL)
            const bytes = sodium.crypto_box_seal(binsec, binkey)
            const encrypted_value = sodium.to_base64(bytes, sodium.base64_variants.ORIGINAL)

            await github.rest.actions.createOrUpdateRepoSecret({
              ...context.repo,
              secret_name: 'REFRESH_TOKEN',
              encrypted_value,
              key_id
            })
